### ISSUE TITLE
家のLAN構成を考える

### ISSUE THREAD

**Issue by 03hcl** [03-family/daily_lives#66]
#61 で TP-Link Archer AX55 を買った
現状のプロバイダとの契約とL2TPのVPN接続の都合を考えると
上記ルーターで v6 Plus モードが使えつつ PPPoE パススルーができる構成にしたい
のちのちのことも考えて有線ルーターをもう一個買うのも含めて検討したい

**Comment by 03hcl** [comment]
有線ルーターは下記条件を満たす中で最安でいいかもしれない

- スループットはせめて1GHz (いわゆる"ギガビット")
- LAN側のポートは4個
- IPv6 パススルー対応

条件を満たせば無線ルーターでもいいかも

**Comment by 03hcl** [comment]
いまのところは AX55 を v6 Plus でなく PPPoE 接続にしてしのいでいる
速度は昨日の夜 (2022-03-31 22:00台) では v6 と変わらないくらい出ていた
(下り, 上りともに400Mbps くらい)

**Comment by 03hcl** [comment]
- 回線のセッション数が 2 の契約
- v4 側の速度は 100BASE でいい
- 100BASE のルーターはあまりがある

なのでスイッチングハブでよさそう

**Comment by 03hcl** [comment]
ONUと現ルーターの中間に設置する
スイッチングハブはギガビット対応のものを買う

**Comment by 03hcl** [comment]
https://s.kakaku.com/review/K0001278622/

**Comment by kakkoten9** [comment]
買った
